### PR TITLE
Dashboard Frontend

### PR DESCRIPTION
**Pull request by b1f6c1c4**

### CODE REVIEW

**Comment by b1f6c1c4** [comment]
@shisoft The backend RESTful API is described here: https://app.swaggerhub.com/apis/b1f6c1c4/e-curtain/1.0.0

**Comment by shisoft** [comment]
Can you please provide a document for the format to the log files while I am working on sketching the API

**Comment by b1f6c1c4** [comment]
@shisoft  https://github.com/b1f6c1c4/e-curtain/blob/master/top/H0-C.cpp#L160-L164

**Comment by shisoft** [comment]
An example file will be great, I still cannot decode the format from your code. It looks like you are trying to write memory to the file but I have no idea about the data layout.

**Comment by b1f6c1c4** [comment]
@shisoft Plz move your stuff to branch `backend` and top-level folder `/backend` and create another pr

**Pull request merged**
